name: PR auto-assignment

# When the workflow will run
on:
  # Triggers the workflow on pull request events
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
    - name: Assign author
      uses: toshimaru/auto-author-assign@v1.1.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Assign maintainer
      uses: pozil/auto-assign-issue@v1.0.3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        assignees: HoutarouOreki
