name: "Publish nuget package"

on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+.*"
    
jobs:
  build_pack_publish:
    name: "Build, pack, publish"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Extract release notes
      run: |
        git log --pretty=format:'%d %s' ${GITHUB_REF} | perl -pe 's| \(.*tag: v(\d+.\d+.\d+(-preview\d{3})?)(, .*?)*\)|\n## \1\n|g' > RELEASE-NOTES
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/}" >> $GITHUB_ENV
    - name: Build HenFwork
      run: dotnet build ./HenFwork/HenFwork.csproj --configuration Release /p:Version=${VERSION}
    - name: Pack HenFwork
      run: dotnet pack ./HenFwork/HenFwork.csproj --configuration Release /p:Version=${VERSION} --no-build --output .
    - name: Push HenFwork nupkg to GitHub Packages
      run: dotnet nuget push HenFwork.${VERSION}.nupkg --source https://nuget.pkg.github.com/Affectionate-Dove/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Push HenFwork nupkg to nuget.org
      run: dotnet nuget push HenFwork.${VERSION}.nupkg --api-key ${NUGET_TOKEN} --source https://api.nuget.org/v3/index.json
      env:
        NUGET_TOKEN: ${{ secrets.HENFWORK_NUGET_TOKEN }}
